[build]
target = "lib/riscv64-unknown-none-elf.json"
rustflags = [
    "-Z", "build-std=core,alloc", 
    "-Z", "relocation-model=pie",
    "-Z", "pre-link-args=ld.lld=-nostdlib"
]

[link]
script = 'config/kernel.ld'
load-address = '0xffff800000100000 - 0x80200000'

[config]
dev = [
    'arch',
    'cap',
    'cons',
    'dup',
    'env',
    'ip',
    'mnt',
    'mntn',
    'pipe',
    'proc',
    'regress',
    'root',
    'segment',
    'srv',
    'uart',
    'ws'
]

ip = [
    'tcp',
    'udp',
    'ipifc',
    'icmp',
    'icmp6',
    'gre'
]

link = [
    'ethermedium',
    'loopbackmedium',
    'netdevmedium'
]

nodev = [
    'kbin',
    'kprof'
]

nouart = [
    'pci'
]
